#!/usr/bin/env python3
"""
generate_balls_proto.py

Generate a UnibotsBallsRandom.proto file with randomized translations for 16 ping-pong balls
(radius 0.02 m) and 24 steel balls (radius 0.01 m). Uses rejection sampling to avoid overlaps.

- Writes to: OxbotsSimulator/Protos/UnibotsBallsRandom.proto (will backup existing file)
- Usage: python3 tools/generate_balls_proto.py
- Optional environment variables / CLI flags could be added; this script is a simple self-contained tool.

Comments in English as requested.
"""
import os
import sys
import math
import random
import time
from datetime import datetime

# ---------- Config ----------
PROJECT_ROOT = os.path.abspath('.')  # adjust if running from other dir
PROTO_DIR = os.path.join(PROJECT_ROOT, 'Protos')
PROTO_PATH = os.path.join(PROTO_DIR, 'UnibotsBallsRandom.proto')
BACKUP_SUFFIX = datetime.now().strftime('%Y%m%d-%H%M%S')

# Arena and placement params
ARENA_SIZE = 2.0      # 2m x 2m arena
MARGIN = 0.10        # keep objects this far from walls
XMIN = -ARENA_SIZE/2 + MARGIN
XMAX =  ARENA_SIZE/2 - MARGIN
ZMIN = -ARENA_SIZE/2 + MARGIN
ZMAX =  ARENA_SIZE/2 - MARGIN

PING_RADIUS = 0.02   # ping-pong
STEEL_RADIUS = 0.01  # steel ball
MAX_ATTEMPTS = 5000
SEED = None          # set to int for reproducible layouts, or None for random

# Visual / physics templates (kept same as your proto snippet)
PING_APPEARANCE = 'PBRAppearance { baseColor 1 0.953 0.008 metalness 0 roughness 1 }'
STEEL_APPEARANCE = 'PBRAppearance { baseColor 0.15 0.5 0.15 roughness 0.15 }'

# ---------- Helper functions ----------
def backup_existing_proto(path):
    if os.path.isfile(path):
        dirname = os.path.dirname(path)
        base = os.path.basename(path)
        bak_name = f"{base}.bak_{BACKUP_SUFFIX}"
        bak_path = os.path.join(dirname, bak_name)
        os.rename(path, bak_path)
        print(f"Backed up existing proto to: {bak_path}")
    else:
        print("No existing proto to back up.")

def rejection_place(counts, radii, xmin, xmax, zmin, zmax, max_attempts=5000):
    """
    counts: list of counts for each category, e.g. [16, 24]
    radii: list of radii for each category, e.g. [0.02, 0.01]
    returns: list of (x,z,radius) in same order (first all ping then all steel)
    """
    placed = []
    results = []
    for cat_idx, cnt in enumerate(counts):
        r = radii[cat_idx]
        for i in range(cnt):
            ok = False
            attempts = 0
            while not ok and attempts < max_attempts:
                attempts += 1
                x = random.uniform(xmin, xmax)
                z = random.uniform(zmin, zmax)
                too_close = False
                for (px, pz, pr) in placed:
                    if math.hypot(px - x, pz - z) < 0.9 * (pr + r):
                        too_close = True
                        break
                if not too_close:
                    placed.append((x, z, r))
                    results.append((x, z, r))
                    ok = True
            if not ok:
                # fallback: place at origin offset (rare)
                print(f"Warning: failed to place item in category {cat_idx} after {max_attempts} attempts; placing at (0,0)")
                results.append((0.0, 0.0, r))
                placed.append((0.0, 0.0, r))
    return results

def make_solid_line(name, radius, x, z, appearance, density):
    """
    Return a single-line Solid block as in your proto snippet.
    (Matches formatting from your original proto.)
    """
    # z coordinate in your proto uses y up? original had translation x z 0.15 where middle value was y?
    # Your original used translation X Z 0.15 with second number as y? Keep same: translation x z 0.15 -> assume (x, z, y)
    # To be safe follow original ordering: translation <x> <z> 0.15
    # BUT in previous proto semantics translation was (x, y, z). Your snippet had e.g. -0.375 -0.375 0.15 seeming (x,z,y)? 
    # We'll use (x, z, 0.15) to match the snippet exactly.
    return (
        f'Solid {{ translation {x:.6f} {z:.6f} 0.15 children [ Shape {{ appearance {appearance} geometry Sphere {{ radius {radius:.2f} }} }} ] '
        f'name "{name}" boundingObject Sphere {{ radius {radius:.2f} }} physics Physics {{ density {density} }} }}'
    )

# ---------- Main ----------
def main():
    if SEED is not None:
        random.seed(SEED)
    else:
        random.seed(time.time())

    os.makedirs(PROTO_DIR, exist_ok=True)
    backup_existing_proto(PROTO_PATH)

    # place 16 ping (radius 0.02) and 24 steel (radius 0.01)
    placements = rejection_place([16, 24], [PING_RADIUS, STEEL_RADIUS], XMIN, XMAX, ZMIN, ZMAX, MAX_ATTEMPTS)
    # placements order: 16 ping, 24 steel

    # build proto content
    header = '#VRML_SIM R2025a utf8\nPROTO UnibotsBalls [] {\n  Group {\n    children [\n\n    # ---- WRAPPED GROUP: generated by generate_balls_proto.py ----\n    DEF BALLS_GROUP Group {\n      children [\n\n'
    footer = '\n      ] # end BALLS_GROUP children\n    } # end DEF BALLS_GROUP\n\n    ] # end children\n  } # end Group\n}\n'

    lines = [header]

    # ping balls
    for i in range(16):
        x, z, r = placements[i]
        name = f'Ping{i+1}'
        density = 50
        lines.append('      ' + make_solid_line(name, r, x, z, PING_APPEARANCE, density))

    # steel balls
    for i in range(24):
        x, z, r = placements[16 + i]
        name = f'Steel{i+1}'
        density = 7800
        lines.append('      ' + make_solid_line(name, r, x, z, STEEL_APPEARANCE, density))

    lines.append(footer)

    # write file
    content = '\n'.join(lines)
    with open(PROTO_PATH, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"Wrote new proto to: {PROTO_PATH}")
    print("Summary of placements (first 5 shown):")
    for idx, (x, z, r) in enumerate(placements[:5]):
        print(f"  {idx+1}: x={x:.3f}, z={z:.3f}, r={r:.3f}")
    print("Done. Please Reset webots world (Pause → Reset) and then Play to reload the new proto.")

if __name__ == '__main__':
    main()